######################### Server configuration ######################
server:
  port: 9090


###################### Spring configurations for database and mail service ################################
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: PayPlanet
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect